"""add analysis_conversations table

Revision ID: 2e11397c963b
Revises: b4c2d1e8f901
Create Date: 2026-08-10 17:27:54.470165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e11397c963b'
down_revision: Union[str, Sequence[str], None] = 'b4c2d1e8f901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_reports_created_at'), table_name='generated_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_generated_reports_created_at'), 'generated_reports', ['created_at'], unique=False)
    # ### end Alembic commands ###
