"""add username to users

Revision ID: 567586ed2c93
Revises: e5b92f71a3c4
Create Date: 2026-08-10 11:10:22.670025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567586ed2c93'
down_revision: Union[str, Sequence[str], None] = 'e5b92f71a3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_reports_created_at'), table_name='generated_reports')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.create_index(op.f('ix_generated_reports_created_at'), 'generated_reports', ['created_at'], unique=False)
    # ### end Alembic commands ###
