"""baseline: per-source KB tables

Revision ID: f8574180196e
Revises:
Create Date: 2026-08-04 13:10:22.699437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8574180196e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('input_hash', sa.String(), nullable=True),
    sa.Column('payload_summary', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('lead', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ghostwriter_findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('gw_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('finding_type', sa.String(length=64), nullable=True),
    sa.Column('replication_steps', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('host_detection', sa.Text(), nullable=True),
    sa.Column('network_detection', sa.Text(), nullable=True),
    sa.Column('affected_entities', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('cve_refs', sa.JSON(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('engagement_code', sa.String(length=64), nullable=True),
    sa.Column('client_name', sa.String(length=256), nullable=True),
    sa.Column('gw_created_at', sa.DateTime(), nullable=True),
    sa.Column('gw_updated_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embed_model', sa.String(length=128), nullable=True),
    sa.Column('qdrant_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghostwriter_findings_client_name'), 'ghostwriter_findings', ['client_name'], unique=False)
    op.create_index(op.f('ix_ghostwriter_findings_content_hash'), 'ghostwriter_findings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ghostwriter_findings_engagement_code'), 'ghostwriter_findings', ['engagement_code'], unique=False)
    op.create_index(op.f('ix_ghostwriter_findings_finding_type'), 'ghostwriter_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_ghostwriter_findings_gw_id'), 'ghostwriter_findings', ['gw_id'], unique=True)
    op.create_index(op.f('ix_ghostwriter_findings_gw_updated_at'), 'ghostwriter_findings', ['gw_updated_at'], unique=False)
    op.create_index(op.f('ix_ghostwriter_findings_project_id'), 'ghostwriter_findings', ['project_id'], unique=False)
    op.create_index(op.f('ix_ghostwriter_findings_qdrant_synced_at'), 'ghostwriter_findings', ['qdrant_synced_at'], unique=False)
    op.create_index(op.f('ix_ghostwriter_findings_severity'), 'ghostwriter_findings', ['severity'], unique=False)
    op.create_table('internal_docs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('mitre_techniques', sa.JSON(), nullable=False),
    sa.Column('validation_steps', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('ref_urls', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embed_model', sa.String(length=128), nullable=True),
    sa.Column('qdrant_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_docs_content_hash'), 'internal_docs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_internal_docs_doc_type'), 'internal_docs', ['doc_type'], unique=False)
    op.create_index(op.f('ix_internal_docs_qdrant_synced_at'), 'internal_docs', ['qdrant_synced_at'], unique=False)
    op.create_table('kb_source_state',
    sa.Column('source_key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('vector_count', sa.Integer(), nullable=False),
    sa.Column('unsynced_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_key')
    )
    op.create_table('mitre_techniques',
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tactics', sa.JSON(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('detection', sa.Text(), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.String(length=16), nullable=True),
    sa.Column('ref_urls', sa.JSON(), nullable=False),
    sa.Column('attack_version', sa.String(length=16), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embed_model', sa.String(length=128), nullable=True),
    sa.Column('qdrant_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('technique_id')
    )
    op.create_index(op.f('ix_mitre_techniques_content_hash'), 'mitre_techniques', ['content_hash'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_deprecated'), 'mitre_techniques', ['deprecated'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_parent_technique_id'), 'mitre_techniques', ['parent_technique_id'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_qdrant_synced_at'), 'mitre_techniques', ['qdrant_synced_at'], unique=False)
    op.create_table('nvd_entries',
    sa.Column('cve_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vuln_status', sa.String(length=32), nullable=True),
    sa.Column('cvss_v3', sa.Float(), nullable=True),
    sa.Column('cvss_v4', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('exploitability_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('attack_vector', sa.String(length=24), nullable=True),
    sa.Column('attack_complexity', sa.String(length=24), nullable=True),
    sa.Column('privileges_required', sa.String(length=24), nullable=True),
    sa.Column('user_interaction', sa.String(length=24), nullable=True),
    sa.Column('confidentiality_impact', sa.String(length=24), nullable=True),
    sa.Column('integrity_impact', sa.String(length=24), nullable=True),
    sa.Column('availability_impact', sa.String(length=24), nullable=True),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=False),
    sa.Column('ref_urls', sa.JSON(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embed_model', sa.String(length=128), nullable=True),
    sa.Column('qdrant_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cve_id')
    )
    op.create_index('ix_nvd_cvss_published', 'nvd_entries', ['cvss_v3', 'published_date'], unique=False)
    op.create_index(op.f('ix_nvd_entries_content_hash'), 'nvd_entries', ['content_hash'], unique=False)
    op.create_index(op.f('ix_nvd_entries_cvss_v3'), 'nvd_entries', ['cvss_v3'], unique=False)
    op.create_index(op.f('ix_nvd_entries_cwe'), 'nvd_entries', ['cwe'], unique=False)
    op.create_index(op.f('ix_nvd_entries_last_modified'), 'nvd_entries', ['last_modified'], unique=False)
    op.create_index(op.f('ix_nvd_entries_published_date'), 'nvd_entries', ['published_date'], unique=False)
    op.create_index(op.f('ix_nvd_entries_qdrant_synced_at'), 'nvd_entries', ['qdrant_synced_at'], unique=False)
    op.create_index(op.f('ix_nvd_entries_severity'), 'nvd_entries', ['severity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Enum('confirmed', 'likely', 'insufficient', 'false_positive', name='verdictenum'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('matched_cves', sa.JSON(), nullable=True),
    sa.Column('matched_techniques', sa.JSON(), nullable=True),
    sa.Column('missing_evidence', sa.JSON(), nullable=True),
    sa.Column('recommended_next_steps', sa.JSON(), nullable=True),
    sa.Column('analyst_confirmed', sa.Boolean(), nullable=True),
    sa.Column('ghostwriter_finding_id', sa.String(), nullable=True),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_engagement_id'), 'findings', ['engagement_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('image_description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_index(op.f('ix_findings_engagement_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_nvd_entries_severity'), table_name='nvd_entries')
    op.drop_index(op.f('ix_nvd_entries_qdrant_synced_at'), table_name='nvd_entries')
    op.drop_index(op.f('ix_nvd_entries_published_date'), table_name='nvd_entries')
    op.drop_index(op.f('ix_nvd_entries_last_modified'), table_name='nvd_entries')
    op.drop_index(op.f('ix_nvd_entries_cwe'), table_name='nvd_entries')
    op.drop_index(op.f('ix_nvd_entries_cvss_v3'), table_name='nvd_entries')
    op.drop_index(op.f('ix_nvd_entries_content_hash'), table_name='nvd_entries')
    op.drop_index('ix_nvd_cvss_published', table_name='nvd_entries')
    op.drop_table('nvd_entries')
    op.drop_index(op.f('ix_mitre_techniques_qdrant_synced_at'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_parent_technique_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_deprecated'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_content_hash'), table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_table('kb_source_state')
    op.drop_index(op.f('ix_internal_docs_qdrant_synced_at'), table_name='internal_docs')
    op.drop_index(op.f('ix_internal_docs_doc_type'), table_name='internal_docs')
    op.drop_index(op.f('ix_internal_docs_content_hash'), table_name='internal_docs')
    op.drop_table('internal_docs')
    op.drop_index(op.f('ix_ghostwriter_findings_severity'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_qdrant_synced_at'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_project_id'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_gw_updated_at'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_gw_id'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_finding_type'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_engagement_code'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_content_hash'), table_name='ghostwriter_findings')
    op.drop_index(op.f('ix_ghostwriter_findings_client_name'), table_name='ghostwriter_findings')
    op.drop_table('ghostwriter_findings')
    op.drop_table('engagements')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
